// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cutoff_amalgamation_cpp_impl
NumericMatrix cutoff_amalgamation_cpp_impl(List sorted_data, NumericVector cutoffs, NumericVector grid);
RcppExport SEXP _OptiThresholdR_cutoff_amalgamation_cpp_impl(SEXP sorted_dataSEXP, SEXP cutoffsSEXP, SEXP gridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type sorted_data(sorted_dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cutoffs(cutoffsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type grid(gridSEXP);
    rcpp_result_gen = Rcpp::wrap(cutoff_amalgamation_cpp_impl(sorted_data, cutoffs, grid));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_OptiThresholdR_cutoff_amalgamation_cpp_impl", (DL_FUNC) &_OptiThresholdR_cutoff_amalgamation_cpp_impl, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_OptiThresholdR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
